# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JUnit Pioneer

on:
  push:
    branches: 'master'
    tags-ignore: 
      - 'v**'
  pull_request:
    branches: '*'

jobs:
#  build:
#    runs-on: ${{ matrix.os }}-latest
#    strategy:
#      matrix:
#        # test against latest update of each major Java version, as well as specific updates of LTS versions:
#        java: [ 8, 11, 14 ]
#        os: [ubuntu, windows, macos]
#    name: Build on ${{ matrix.os }} with Java ${{ matrix.java }}
#    steps:
#      - name: Check out repo
#        uses: actions/checkout@v2
#        # fetch unshallow to enable blame for Sonar
#      - name: Fetch unshallow
#        run: git fetch --prune --unshallow
#      - name: Setup java
#        uses: actions/setup-java@v1
#        with:
#          java-version: ${{ matrix.java }}
#      - name: Cache Gradle
#        uses: actions/cache@v2
#        with:
#          path: ~/.gradle/caches/
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
#          restore-keys: ${{ runner.os }}-gradle-
#      - name: Cache Sonar
#        uses: actions/cache@v2
#        if: matrix.java == '11' && matrix.os == 'ubuntu'
#        with:
#          path: ~/.sonar/cache/
#          key: ${{ runner.os }}-sonar
#      - name: Gradle build
#        uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: --refresh-dependencies --stacktrace --scan clean build
#          wrapper-cache-enabled: false
#      - name: Sonarqube
#        if: matrix.java == '11' && matrix.os == 'ubuntu'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: "61ab2579215aa8a0024a2f9368fc1298fdecfd18"
#        run: ./gradlew jacocoTestReport sonarqube --stacktrace -i

  junitVersions:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        junit: ['5.0', '5.1', '5.2', '6.0', '6.1', '6.2']
    name: build for JunitVersion 5.${{ matrix.junit }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Gradle build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --refresh-dependencies --stacktrace --scan clean build -PjunitVersion=${{ matrix.junit }}
          wrapper-cache-enabled: false

  javaExperimental:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: build with nightly gradle and Java
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 15-ea
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Gradle build
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          arguments: --refresh-dependencies --stacktrace --scan clean build -PjunitVersion=${{ matrix.junit }}
          wrapper-cache-enabled: false